apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        component: rabbitmq
      name: rabbitmq
    spec:
      sessionAffinity: ClientIP
      ports:
        - port: 5672
          name: main
        - port: 15672
          name: management
      selector:
        component: rabbitmq
  - apiVersion: v1
    kind: ReplicationController
    metadata:
      labels:
        component: rabbitmq
      name: rabbitmq-controller
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            component: rabbitmq
        spec:
          containers:
            - image: rabbitmq:management
              name: rabbitmq
              ports:
                - containerPort: 5672
                - containerPort: 15672
              resources:
                limits:
                  cpu: 100m
