apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        db: rethinkdb
      name: rethinkdb-driver
    spec:
      sessionAffinity: ClientIP
      ports:
        - port: 28015
          targetPort: 28015
          name: driver
        - port: 80
          targetPort: 8080
          name: web
      selector:
        db: rethinkdb
  - apiVersion: v1
    kind: ReplicationController
    metadata:
      labels:
        db: rethinkdb
      name: rethinkdb-rc
    spec:
      replicas: 1
      selector:
        db: rethinkdb
        role: replicas
      template:
        metadata:
          labels:
            db: rethinkdb
            role: replicas
        spec:
          containers:
            - image: rethinkdb
              name: rethinkdb
              command:
                - rethinkdb
                - --bind
                - all
                - -n
                - rethinkdb
              ports:
                - containerPort: 8080
                  name: admin-port
                - containerPort: 28015
                  name: driver-port
                - containerPort: 29015
                  name: cluster-port
