variable "storages"          { }
variable "nodes"             { }
variable "instance_type"     { }
variable "ssh_key"           { }
variable "subnet"            { }
variable "peers"             { }
variable "token"             { }
variable "zone"              { }
variable "region"            { }
